# Generated by Django 4.1.5 on 2023-01-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contact_company_name_alter_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
